version: v0.2.21
general:
  show_hidden: false
  table:
    header:
      cols:
        - format: │     path
          style:
            fg: ~
            bg: ~
            add_modifier:
              bits: 0
            sub_modifier:
              bits: 0
        - format: type
          style:
            fg: ~
            bg: ~
            add_modifier:
              bits: 0
            sub_modifier:
              bits: 0
        - format: " index"
          style:
            fg: ~
            bg: ~
            add_modifier:
              bits: 0
            sub_modifier:
              bits: 0
      style:
        fg: ~
        bg: ~
        add_modifier:
          bits: 1
        sub_modifier:
          bits: 0
      height: 1
    row:
      cols:
        - format: "{{{tree}}}{{{prefix}}}{{{icon}}} {{{relativePath}}}{{#if isDir}}/{{/if}}{{{suffix}}}"
          style:
            fg: ~
            bg: ~
            add_modifier:
              bits: 0
            sub_modifier:
              bits: 0
        - format: "{{{mimeEssence}}}"
          style:
            fg: ~
            bg: ~
            add_modifier:
              bits: 0
            sub_modifier:
              bits: 0
        - format: "{{#if isBeforeFocus}}-{{else}} {{/if}}{{{relativeIndex}}}/{{{index}}}/{{{total}}}"
          style:
            fg: ~
            bg: ~
            add_modifier:
              bits: 0
            sub_modifier:
              bits: 0
      style:
        fg: ~
        bg: ~
        add_modifier:
          bits: 0
        sub_modifier:
          bits: 0
      height: 0
    style:
      fg: ~
      bg: ~
      add_modifier:
        bits: 0
      sub_modifier:
        bits: 0
    tree:
      - format: ├─
        style:
          fg: ~
          bg: ~
          add_modifier:
            bits: 0
          sub_modifier:
            bits: 0
      - format: ├─
        style:
          fg: ~
          bg: ~
          add_modifier:
            bits: 0
          sub_modifier:
            bits: 0
      - format: ╰─
        style:
          fg: ~
          bg: ~
          add_modifier:
            bits: 0
          sub_modifier:
            bits: 0
    col_spacing: 3
    col_widths:
      - percentage: 60
      - percentage: 20
      - percentage: 20
  normal_ui:
    prefix: "  "
    suffix: ""
    style:
      fg: ~
      bg: ~
      add_modifier:
        bits: 0
      sub_modifier:
        bits: 0
  focused_ui:
    prefix: "▸["
    suffix: "]"
    style:
      fg: Blue
      bg: ~
      add_modifier:
        bits: 1
      sub_modifier:
        bits: 0
  selection_ui:
    prefix: " {"
    suffix: "}"
    style:
      fg: LightGreen
      bg: ~
      add_modifier:
        bits: 1
      sub_modifier:
        bits: 0
filetypes:
  directory:
    icon: ð
    style:
      fg: Blue
      bg: ~
      add_modifier:
        bits: 1
      sub_modifier:
        bits: 0
  file:
    icon: ƒ
    style:
      fg: ~
      bg: ~
      add_modifier:
        bits: 0
      sub_modifier:
        bits: 0
  symlink:
    icon: §
    style:
      fg: Cyan
      bg: ~
      add_modifier:
        bits: 4
      sub_modifier:
        bits: 0
  mime_essence: {}
  extension: {}
  special: {}
modes:
  number:
    name: number
    help: ~
    extra_help: ~
    key_bindings:
      on_key:
        backspace:
          help: clear
          messages:
            - ResetInputBuffer
        ctrl-c:
          help: cancel & quit
          messages:
            - Terminate
        down:
          help: "to down [j]"
          messages:
            - FocusNextByRelativeIndexFromInput
            - SwitchMode: default
        enter:
          help: to index
          messages:
            - FocusByIndexFromInput
            - SwitchMode: default
        j:
          help: ~
          messages:
            - FocusNextByRelativeIndexFromInput
            - SwitchMode: default
        k:
          help: ~
          messages:
            - FocusPreviousByRelativeIndexFromInput
            - SwitchMode: default
        up:
          help: "to up [k]"
          messages:
            - FocusPreviousByRelativeIndexFromInput
            - SwitchMode: default
      on_alphabet: ~
      on_number:
        help: input
        messages:
          - BufferInputFromKey
      on_special_character: ~
      default:
        help: ~
        messages:
          - SwitchMode: default
  create file:
    name: create file
    help: ~
    extra_help: ~
    key_bindings:
      on_key:
        backspace:
          help: clear
          messages:
            - SetInputBuffer: ""
        ctrl-c:
          help: cancel & quit
          messages:
            - Terminate
        enter:
          help: create file
          messages:
            - BashExec: "PTH=\"${XPLR_INPUT_BUFFER:?}\"\nif touch \"${PTH:?}\"; then\n  echo \"LogSuccess: $PTH created\" >> \"${XPLR_PIPE_MSG_IN:?}\"\n  echo Explore >> \"${XPLR_PIPE_MSG_IN:?}\"\nelse\n  echo \"LogError: failed to create $PTH\" >> \"${XPLR_PIPE_MSG_IN:?}\"\n  echo Refresh >> \"${XPLR_PIPE_MSG_IN:?}\"\nfi\n"
            - SwitchMode: default
        esc:
          help: cancel
          messages:
            - SwitchMode: default
      on_alphabet: ~
      on_number: ~
      on_special_character: ~
      default:
        help: ~
        messages:
          - BufferInputFromKey
  selection ops:
    name: selection ops
    help: ~
    extra_help: ~
    key_bindings:
      on_key:
        c:
          help: copy here
          messages:
            - BashExec: "(while IFS= read -r line; do\n  if cp -v \"${line:?}\" ./; then\n    echo \"LogSuccess: $line copied to $PWD\" >> \"${XPLR_PIPE_MSG_IN:?}\"\n  else\n    echo \"LogError: failed to copy $line to $PWD\" >> \"${XPLR_PIPE_MSG_IN:?}\"\n  fi\ndone <<< \"${XPLR_SELECTION:?}\")\necho Explore >> \"${XPLR_PIPE_MSG_IN:?}\"\necho ClearSelection >> \"${XPLR_PIPE_MSG_IN:?}\"\nread -p \"[enter to continue]\"\n"
            - SwitchMode: default
        ctrl-c:
          help: cancel & quit
          messages:
            - Terminate
        m:
          help: move here
          messages:
            - BashExec: "(while IFS= read -r line; do\n  if mv -v \"${line:?}\" ./; then\n    echo \"LogSuccess: $line moved to $PWD\" >> \"${XPLR_PIPE_MSG_IN:?}\"\n  else\n    echo \"LogError: failed to move $line to $PWD\" >> \"${XPLR_PIPE_MSG_IN:?}\"\n  fi\ndone <<< \"${XPLR_SELECTION:?}\")\necho Explore >> \"${XPLR_PIPE_MSG_IN:?}\"\nread -p \"[enter to continue]\"\n"
            - SwitchMode: default
      on_alphabet: ~
      on_number: ~
      on_special_character: ~
      default:
        help: ~
        messages:
          - SwitchMode: default
  go to:
    name: go to
    help: ~
    extra_help: ~
    key_bindings:
      on_key:
        ctrl-c:
          help: cancel & quit
          messages:
            - Terminate
        g:
          help: top
          messages:
            - FocusFirst
            - SwitchMode: default
        x:
          help: open in gui
          messages:
            - BashExec: "xdg-open \"${XPLR_FOCUS_PATH:?}\" &> /dev/null\n"
            - SwitchMode: default
      on_alphabet: ~
      on_number: ~
      on_special_character: ~
      default:
        help: ~
        messages:
          - SwitchMode: default
  rename:
    name: rename
    help: ~
    extra_help: ~
    key_bindings:
      on_key:
        backspace:
          help: clear
          messages:
            - SetInputBuffer: ""
        ctrl-c:
          help: cancel & quit
          messages:
            - Terminate
        enter:
          help: rename
          messages:
            - BashExec: "SRC=\"${XPLR_FOCUS_PATH:?}\"\nTARGET=\"${XPLR_INPUT_BUFFER:?}\"\nif mv -v \"${SRC:?}\" \"${TARGET:?}\"; then\n  echo \"LogSuccess: $SRC renamed to $TARGET\" >> \"${XPLR_PIPE_MSG_IN:?}\"\n  echo Explore >> \"${XPLR_PIPE_MSG_IN:?}\"\nelse\n  echo \"LogError: failed to rename $SRC to $TARGET\" >> \"${XPLR_PIPE_MSG_IN:?}\"\nfi\n"
            - SwitchMode: default
        esc:
          help: cancel
          messages:
            - SwitchMode: default
      on_alphabet: ~
      on_number: ~
      on_special_character: ~
      default:
        help: ~
        messages:
          - BufferInputFromKey
  default:
    name: default
    help: ~
    extra_help: ~
    key_bindings:
      on_key:
        "#":
          help: ~
          messages:
            - PrintAppStateAndQuit
        ".":
          help: show hidden
          messages:
            - ToggleNodeFilter:
                filter: RelativePathDoesNotStartWith
                input: "."
                case_sensitive: false
            - Explore
        /:
          help: ~
          messages:
            - ResetNodeFilters
            - SwitchMode: search
            - SetInputBuffer: ""
            - Explore
        ":":
          help: action
          messages:
            - SwitchMode: action
        "?":
          help: global help menu
          messages:
            - BashExec: "echo -e \"${XPLR_GLOBAL_HELP_MENU}\"\necho\nread -p \"[enter to continue]\"\n"
        G:
          help: go to bottom
          messages:
            - FocusLast
        ctrl-c:
          help: "cancel & quit [q|esc]"
          messages:
            - Terminate
        ctrl-f:
          help: "search [/]"
          messages:
            - ResetNodeFilters
            - SwitchMode: search
            - SetInputBuffer: ""
            - Explore
        d:
          help: delete
          messages:
            - SwitchMode: delete
        down:
          help: "down [j]"
          messages:
            - FocusNext
        enter:
          help: quit with result
          messages:
            - PrintResultAndQuit
        esc:
          help: ~
          messages:
            - Terminate
        g:
          help: go to
          messages:
            - SwitchMode: go to
        h:
          help: ~
          messages:
            - Back
        j:
          help: ~
          messages:
            - FocusNext
        k:
          help: ~
          messages:
            - FocusPrevious
        l:
          help: ~
          messages:
            - Enter
        left:
          help: "back [h]"
          messages:
            - Back
        q:
          help: ~
          messages:
            - Terminate
        r:
          help: rename
          messages:
            - SwitchMode: rename
            - BashExec: "echo \"SetInputBuffer: $(basename ${XPLR_FOCUS_PATH})\" >> \"${XPLR_PIPE_MSG_IN:?}\"\n"
        right:
          help: "enter [l]"
          messages:
            - Enter
        space:
          help: "toggle selection [v]"
          messages:
            - ToggleSelection
            - FocusNext
        up:
          help: "up [k]"
          messages:
            - FocusPrevious
        v:
          help: ~
          messages:
            - ToggleSelection
            - FocusNext
      on_alphabet: ~
      on_number:
        help: input
        messages:
          - ResetInputBuffer
          - SwitchMode: number
          - BufferInputFromKey
      on_special_character: ~
      default:
        help: ~
        messages:
          - SwitchMode: default
  create:
    name: create
    help: ~
    extra_help: ~
    key_bindings:
      on_key:
        ctrl-c:
          help: cancel & quit
          messages:
            - Terminate
        d:
          help: create directory
          messages:
            - SwitchMode: create directory
            - SetInputBuffer: ""
        esc:
          help: cancel
          messages:
            - SwitchMode: default
        f:
          help: create file
          messages:
            - SwitchMode: create file
            - SetInputBuffer: ""
      on_alphabet: ~
      on_number: ~
      on_special_character: ~
      default:
        help: ~
        messages:
          - SwitchMode: default
  delete:
    name: delete
    help: ~
    extra_help: ~
    key_bindings:
      on_key:
        D:
          help: force delete
          messages:
            - BashExec: "(while IFS= read -r line; do\n  if rm -rfv \"${line:?}\"; then\n    echo \"LogSuccess: $line deleted\" >> \"${XPLR_PIPE_MSG_IN:?}\"\n  else\n    echo \"LogError: failed to delete $line\" >> \"${XPLR_PIPE_MSG_IN:?}\"\n  fi\ndone <<< \"${XPLR_RESULT:?}\")\necho Explore >> \"${XPLR_PIPE_MSG_IN:?}\"\nread -p \"[enter to continue]\"\n"
            - SwitchMode: default
            - Explore
        ctrl-c:
          help: cancel & quit
          messages:
            - Terminate
        d:
          help: delete
          messages:
            - BashExec: "(while IFS= read -r line; do\n  if [ -d \"$line\" ]; then\n    if rmdir -v \"${line:?}\"; then\n      echo \"LogSuccess: $line deleted\" >> \"${XPLR_PIPE_MSG_IN:?}\"\n    else\n      echo \"LogError: failed to delete $line\" >> \"${XPLR_PIPE_MSG_IN:?}\"\n    fi\n  else\n    if rm -v \"${line:?}\"; then\n      echo \"LogSuccess: $line deleted\" >> \"${XPLR_PIPE_MSG_IN:?}\"\n    else\n      echo \"LogError: failed to delete $line\" >> \"${XPLR_PIPE_MSG_IN:?}\"\n    fi\n  fi\ndone <<< \"${XPLR_RESULT:?}\")\necho Explore >> \"${XPLR_PIPE_MSG_IN:?}\"\nread -p \"[enter to continue]\"\n"
            - SwitchMode: default
      on_alphabet: ~
      on_number: ~
      on_special_character: ~
      default:
        help: ~
        messages:
          - SwitchMode: default
  create directory:
    name: create directory
    help: ~
    extra_help: ~
    key_bindings:
      on_key:
        backspace:
          help: clear
          messages:
            - SetInputBuffer: ""
        ctrl-c:
          help: cancel & quit
          messages:
            - Terminate
        enter:
          help: create directory
          messages:
            - BashExec: "PTH=\"${XPLR_INPUT_BUFFER:?}\"\nif mkdir -p \"$PTH\"; then\n  echo Explore >> \"${XPLR_PIPE_MSG_IN:?}\"\n  echo \"LogSuccess: $PTH created\" >> \"${XPLR_PIPE_MSG_IN:?}\"\nelse\n  echo \"LogError: failed to create $PTH\" >> \"${XPLR_PIPE_MSG_IN:?}\"\nfi\n"
            - SwitchMode: default
        esc:
          help: cancel
          messages:
            - SwitchMode: default
      on_alphabet: ~
      on_number: ~
      on_special_character: ~
      default:
        help: ~
        messages:
          - BufferInputFromKey
  action:
    name: action to
    help: ~
    extra_help: ~
    key_bindings:
      on_key:
        "!":
          help: shell
          messages:
            - Call:
                command: bash
                args: []
            - Explore
            - SwitchMode: default
        c:
          help: create
          messages:
            - SwitchMode: create
        ctrl-c:
          help: "cancel & quit [q]"
          messages:
            - Terminate
        l:
          help: logs
          messages:
            - BashExec: "echo -e \"$XPLR_LOGS\"\nread -p \"[enter to continue]\"\n"
            - SwitchMode: default
        q:
          help: ~
          messages:
            - Terminate
        s:
          help: selection operations
          messages:
            - SwitchMode: selection ops
      on_alphabet: ~
      on_number:
        help: go to index
        messages:
          - ResetInputBuffer
          - SwitchMode: number
          - BufferInputFromKey
      on_special_character: ~
      default:
        help: ~
        messages:
          - SwitchMode: default
  search:
    name: search
    help: ~
    extra_help: ~
    key_bindings:
      on_key:
        backspace:
          help: clear
          messages:
            - SetInputBuffer: ""
            - ResetNodeFilters
            - Explore
        ctrl-c:
          help: cancel & quit
          messages:
            - Terminate
        down:
          help: down
          messages:
            - FocusNext
        enter:
          help: focus
          messages:
            - ResetNodeFilters
            - SwitchMode: default
            - Explore
        esc:
          help: cancel
          messages:
            - ResetNodeFilters
            - SwitchMode: default
            - Explore
        left:
          help: back
          messages:
            - ResetNodeFilters
            - Back
            - SwitchMode: default
            - Explore
        right:
          help: enter
          messages:
            - ResetNodeFilters
            - Enter
            - SwitchMode: default
            - Explore
        up:
          help: up
          messages:
            - FocusPrevious
      on_alphabet: ~
      on_number: ~
      on_special_character: ~
      default:
        help: ~
        messages:
          - BufferInputFromKey
          - ResetNodeFilters
          - AddNodeFilterFromInput:
              filter: RelativePathDoesContain
              case_sensitive: false
          - Explore
